name: Deploy to dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4  # Update to the latest version

      - uses: databricks/setup-cli@main
